# Generated by Django 4.2.8 on 2026-01-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(help_text='Write content in Markdown format'),
        ),
    ]
